site_name: ALGO
nav:
- Home : index.md
- API : src/basic.md
- Example : src/example.md
theme:
  name: material
use_directory_urls: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true


copyright: Contact Info

extra:
  social:
    - icon : fontawesome/brands/github
      link: https://github.com
      name: github
    - icon: fontawesome/regular/envelope
      name: Contact via Email
      link: mailto:your_email@your_host.com
      

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js